export const QUERY_IDS: Record<string, number> = {
  daily_launches: 6773306,
  daily_volume: 6773308,
  graduation_rate: 6773311,
  fee_revenue: 6773313,
  trade_size_dist: 6773326,
  token_survival: 6773327,
  bonding_curve: 6773328,
  top_traders_pnl: 6773330,
  whale_tracker: 6773331,
  sandwich_detection: 6773332,
  bot_activity: 6773333,
  hourly_pattern: 6773334,
  price_impact: 6773335,
  creator_leaderboard: 6773337,
  new_vs_returning: 6773338,
  fee_by_curve_stage: 6773339,
  fee_vs_survival: 6773340,
  variable_fee_model: 6773341,
  fee_curve_granular: 6773343,
  bot_market_share: 6773358,
  sandwich_profit: 6773359,
  smart_money: 6773360,
  mev_impact_rate: 6773363,
  pumpswap_volume: 6773615,
  pumpswap_fees: 6773617,
  migration_funnel: 6773618,
  pumpswap_top_pools: 6773619,
  pumpswap_liquidity: 6773620,
  mev_bot_strategy: 6773622,
  competitor_dex_share: 6773666,
  competitor_launches: 6773667,
  competitor_grad_rates: 6773669,
  // Deep Dives
  cohort_retention: 6774041,
  revenue_quality: 6774054,
  post_grad_survival: 6774063,
  curve_velocity: 6774071,
};

export const PARAMETERIZED = new Set([
  "daily_launches",
  "daily_volume",
  "graduation_rate",
  "fee_revenue",
  "bot_activity",
  "price_impact",
  "new_vs_returning",
  "pumpswap_volume",
  "pumpswap_fees",
  "migration_funnel",
  "pumpswap_liquidity",
]);

export const QUERY_DESCRIPTIONS: Record<string, string> = {
  daily_launches: "Daily token launches on Pump.fun",
  daily_volume: "Daily trading volume, traders, and buy/sell breakdown",
  graduation_rate: "Daily graduation rate (% of tokens completing bonding curve)",
  fee_revenue: "Daily protocol + creator fee revenue",
  trade_size_dist: "Trade size distribution buckets",
  token_survival: "Token lifespan distribution",
  bonding_curve: "Bonding curve progress distribution",
  top_traders_pnl: "Top traders by PnL (7d)",
  whale_tracker: "Whale activity tracker (7d)",
  sandwich_detection: "Daily sandwich attack detection",
  bot_activity: "Bot trading activity over time",
  hourly_pattern: "Intraday trading pattern (UTC)",
  price_impact: "Price impact / slippage percentiles",
  creator_leaderboard: "Top creator fee earners",
  new_vs_returning: "New vs returning traders daily",
  fee_by_curve_stage: "Fee breakdown by bonding curve stage",
  fee_vs_survival: "Fee rate vs token survival correlation",
  variable_fee_model: "Variable fee model comparisons",
  fee_curve_granular: "Granular fee curve by reserve level",
  bot_market_share: "Bot market share breakdown",
  sandwich_profit: "Sandwich attack profitability",
  smart_money: "Smart money wallet tracking",
  mev_impact_rate: "MEV impact rate on trades",
  pumpswap_volume: "PumpSwap AMM daily volume & traders",
  pumpswap_fees: "PumpSwap 3-way fee split analysis",
  migration_funnel: "Token lifecycle funnel: create → graduate → migrate",
  pumpswap_top_pools: "Top PumpSwap pools by volume (7d)",
  pumpswap_liquidity: "PumpSwap liquidity depth over time",
  mev_bot_strategy: "MEV bot strategy classification",
  competitor_dex_share: "DEX volume market share across Solana (30d)",
  competitor_launches: "Token launches by launchpad platform (30d)",
  competitor_grad_rates: "Graduation rates by launchpad platform (30d)",
  cohort_retention: "Weekly wallet cohort retention analysis (8-week window)",
  revenue_quality: "Revenue quality: ARPU, concentration, durability",
  post_grad_survival: "Post-graduation token survival curve",
  curve_velocity: "Bonding curve velocity (time-to-graduate distribution)",
};
